#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"


scope="$1" && shift
input="${1:-$(</dev/stdin)}"

case $scope in

	text.newlines ) echo "$input" | awk '{ printf "%s\\n", $0 }' ;;

	url.encode ) echo "$input" | jq -s -R -r @uri ;;
	url.decode ) echo "$input" | perl -pe 's/%([0-9a-f]{2})/sprintf("%s", pack("H2",$1))/eig' ;;

	base64.encode ) echo "$input" | jq -s -R -r @base64 ;;
	base64.decode ) echo "$input" | perl -MMIME::Base64 -ne 'print decode_base64($_)' ;;

	hex.encode ) echo "$input" | xxd -ps ;;
	hex.decode ) echo "$input" | xxd -r -p ;;

	html.encode ) echo "$input" | jq -j -s -R -r @html ;;
	html.decode ) echo "$input" | php -R 'echo html_entity_decode($argn, ENT_QUOTES|ENT_HTML5) . "\n";' ;;

esac