#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"


command="$1" && shift

case $command in


	# =============================================================================
	math )

		while getopts "f:c:o:" opt; do
			case $opt in
				f ) file=$OPTARG ;; #file to perform operations on
				c ) columns=$OPTARG ;; #columns given as comma separated list
				o ) operation=$OPTARG ;; #operation to perform
				\? ) echo "Invalid option: -$OPTARG" >&2 ;;
			esac
		done

		[[ -z $file ]] && echo "No file specified to perform operations on" && exit 1
		[[ -z $columns ]] && echo "No columns specified to perform math on" && exit 1

		declare -a valid_operations=( sum mean median mode min max range variance std_dev unique count )

		# Check if operation is valid
		valid=false
		for valid_operation in "${valid_operations[@]}"; do
			if [[ $valid_operation == "$operation" ]]; then
			valid=true
			break
			fi
		done

		if [[ $valid == true ]]; then
			csvstat -c "$columns" --"$operation" "$file"
		else
			b/error invalid_operation "Invalid operation: $operation"
		fi

		;;



	# =============================================================================
	limit )

		while getopts "f:o:" opt; do
			case $opt in
				f ) file=$OPTARG ;; #file to perform operations on
				o ) output_file=$OPTARG ;; #output file
				\? ) echo "Invalid option: -$OPTARG" >&2 ;;
			esac
		done

		limit="${1:-10}"

		[[ -z $file ]] && echo "No file specified to perform operations on" && exit 1

		if [[ -n $output_file ]]; then
			csvlook -n "$file" > "$output_file"
		else
			csvlook -n "$file"
		fi

		;;



	# =============================================================================
	dedupe )

		while getopts "f:o:d:" opt; do
			case $opt in
				f ) file=$OPTARG ;; #file to perform operations on
				o ) output=$OPTARG ;; #output deduped
				d ) columns=$OPTARG ;; #columns given as comma separated list
				\? ) echo "Invalid option: -$OPTARG" >&2 ;;
			esac
		done

		;;



	# =============================================================================
	filter )

		while getopts "f:c:m:b:C" opt; do
			case $opt in
				f ) file=$OPTARG ;; #file to perform operations on
				c ) columns=$OPTARG ;; #columns given as comma separated list
				m ) match=$OPTARG ;; #match string
				b ) begins_with=$OPTARG ;; #match string
				C ) case_insensitive=true ;; #case insensitive match
				\? ) echo "Invalid option: -$OPTARG" >&2 ;;
			esac
		done

		;;



esac