#!/usr/bin/env bash
# Useful date and time functions and visuals

source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

[[ -z $1 ]] && b/usage -w 8 -t "commands" $0 \
	next		"  Various next dates and keywords" \
	last		"  Various previous dates and keywords" \
	cal			"  Print calendar(s)" \
	date		"* Print the current date and time" \
	stamp		"  Print the current date and time in a timestamp format" \
	countdown	"  Print a countdown to a given date and time" \
	add			"  Add a given number of days to the current date" \
	subtract	"  Subtract a given number of days from the current date" \
	format		"  Format a given date and time string" \
	parse		"  Parse a given date and time string" && exit 0

command="$1" && shift

case $command in

	cal ) cal "$@" ;;

	# date, January 1, 1970 style
	date ) date -f "%A, %B %d, %Y" ;;

	stamp ) date +%s ;;

	countdown ) 
		[[ -z $1 ]] && b/usage -w 8 -t "options" $0 \
			"<date>"	"* The date and time to count down to" \
			"-f"		"  The format of the date and time"
		[[ -z $2 ]] && b/error arg_error "Please provide a date and time to count down to"
		[[ -z $3 ]] && b/error arg_error "Please provide a format for the date and time"
		[[ -n $1 && -n $2 ]] && b/countdown $1 $2
		;;

	diff )

		;;

	format ) 

		;;

	* )
		b/error invalid_command "Invalid command: $command"
esac