#!/usr/bin/env bash
# Date functions, calendars, and reminders
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

# ================================== DOC ===================================

declare doc_name="date"
declare doc_description="Date functions, calendars, and reminders"

declare -a doc_options=(
	"cal"		"Print a calendar"
	"date"		"Print the current date and time"
	"stamp"		"Print the current date and time in a timestamp format"
	"countdown"	"Print a countdown to a given date and time"
	"add"		"Add a given number of days to the current date"
	"subtract"	"Subtract a given number of days from the current date"
	"format"	"Format a given date and time string"
	"parse"		"Parse a given date and time string"
) && [[ "$1" == '--inspect' ]] && return 0

# ==========================================================================



command="$1" && shift

case $command in

	cal )
	
		# ============== DOC ==============
		doc_name+=" cal"
		doc_description="Print a calendar"
		declare -a doc_options=(
			"-m"		"  The month to print a calendar for"
			"-y"		"  The year to print a calendar for"
		) && [[ "$1" == '--inspect' ]] && return 0
		# ================================

		cal "$@" ;;

	# date, January 1, 1970 style
	date )
		;;

	stamp )
		;;

	countdown ) 
		;;

	diff )

		;;

	format ) 

		;;
esac