#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

doc=$(cat <<'EOF'

# doc

View documentation for a command

`<:scope> (:command)`	| View documentation for a scope (and optionally a command of that scope)

> doc openai		| View documentation for the `openai` scope
> doc openai chat 	| View documentation for the `openai chat` command

EOF
) && export doc && inspect "$1"

command="$1" && shift

# Handle the command
case $command in
	
	--inspect ) inspect ;;

	* )

		# Loop over the executables in the b/ directory
		for executable in "$BARE_DIR/b"/*; do
			executable=$(basename "$executable")

			# If the command matches the executable
			if [[ "$command" == "$executable" ]]; then
				source "$BARE_DIR/b/$executable" "$@" --inspect && exit 0
			fi
		done

		# If we've gotten this far, the command is not a valid scope
		echo "Invalid command: $command" && exit 1

		;;
		
esac