#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

# Define the documentation in JSON format
declare -x doc='{
	"name": "doc",
	"description": "Takes a script from the b/ directory and generates a markdown file with the script'\''s documentation.",
	"options": [
		{
			"name": ":scope",
			"description": "Prints the documentation for the given scope"
		}
	]
}'

# Get the command from the arguments
command="$1" && shift

# Handle the command
case $command in
	
	--inspect ) inspect ;;

	* )
		# Loop over the executables in the b/ directory
		for executable in "$BARE_DIR/b"/*; do
			executable=$(basename "$executable")

			# If the command matches the executable
			if [[ "$command" == "$executable" ]]; then
				source "$BARE_DIR/b/$executable" --inspect
			fi
		done

		# If we've gotten this far, the command is not a valid scope
		echo "Invalid command: $command" && exit 1

		;;
		
esac