#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")/../" && { [ -f lib/init ] && source lib/init; } || { echo "Cannot find lib/init"; exit 1; }

[[ -z "$1" ]] && b/usage -w 4 $0 \
    ':1' "* error_code" \
    ':2' "  description" && exit 0

printf "\n❌ ${red}$1${reset}: $2\n\n" && exit 1