#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

[[ -z "$1" ]] && b/usage -w 4 $0 \
    ':1' "* error_code" \
    ':2' "  description" && exit 0

printf "\n❌ ${red}$1${reset}: $2\n\n" && exit 1