#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"


command="$1" && shift

case $command in

	# =============================================================================
	digital-ocean )

		[[ -z $BARE_DO_SPACES_ACCESS_KEY ]] && echo "No Digital Ocean Spaces key found" && exit 1
		[[ -z $BARE_DO_SPACES_SECRET ]] && echo "No Digital Ocean Spaces secret found" && exit 1

		key=$BARE_DO_SPACES_ACCESS_KEY
		secret=$BARE_DO_SPACES_SECRET
		public=false
		while getopts "f:p:Pk:s:" opt; do
			case $opt in
				f ) file=$OPTARG ;; # file to export
				p ) path=$OPTARG ;; # DO path to export to
				P ) public=true ;;
				k ) key=$OPTARG ;;
				s ) secret=$OPTARG ;;
				\? ) echo "Invalid option: -$OPTARG" >&2 ;;
			esac
		done

		[[ -z $file ]] && echo "No file specified to export" && exit 1
		[[ -z $path ]] && echo "No DO path specified to export to" && exit 1
		[[ -z $key ]] && echo "No key specified to use" && exit 1
		[[ -z $secret ]] && echo "No secret specified to use" && exit 1

		# get the mime type of the file
		content_type=$(file --mime-type -b "$file")

		STORAGETYPE="STANDARD"

		space_path="/$path"
		space="${BARE_DO_SPACE}"
		date=$(date +"%a, %d %b %Y %T %z")
		[ "$public" == true ] && acl="x-amz-acl:public-read" || acl="x-amz-acl:private"
		storage_type="x-amz-storage-class:${STORAGETYPE}"
		string="PUT\n\n$content_type\n$date\n$acl\n$storage_type\n/$space$space_path"
		signature=$(echo -en "${string}" | openssl sha1 -hmac "${BARE_DO_SPACES_SECRET}" -binary | base64)
		response=$(curl -s -X PUT -T "$BARE_HOME/.nb/$file" \
		-H "Host: $space.${BARE_DO_REGION}.digitaloceanspaces.com" \
		-H "Date: $date" \
		-H "Content-Type: $content_type" \
		-H "$storage_type" \
		-H "$acl" \
		-H "Authorization: AWS ${BARE_DO_SPACES_ACCESS_KEY}:$signature" \
		"https://$space.${BARE_DO_REGION}.digitaloceanspaces.com$space_path")

		# echo the digital ocean url of the file
		echo "https://$space.${BARE_DO_REGION}.digitaloceanspaces.com$space_path"

		;;

	* ) echo "Invalid command: $command" && exit 1 ;;
	
esac