#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

doc="$(cat <<'EOF'

# geo

Geographical information

`:city|ip`	| Get the 'latitue,longitude' for a give IP address or city

> geo 130.23.11.299		| Get details of given an IP address
> geo "asheville nc"	| Get details a city

EOF
)" && inspect "$doc" "$1"
# =============================================================================

get_location() {
	if [[ -z $1 ]]; then
		echo $(curl -sL https://ipinfo.io/ip)
	else
		echo $(b/codec url.encode "$1")
	fi
}

get_coordinates() {
	local location=$1
	local type=$2

	if [[ $type == "city" ]]; then
		curl -s "https://nominatim.openstreetmap.org/search?format=json&q=$location" | jq -r '.[0].lat + "," + .[0].lon' | awk -F, '{printf "%.2f,%.2f\n", $1, $2}'
	else
		curl -s "https://ipinfo.io/$location" | jq -r '.loc' | awk -F, '{printf "%.2f,%.2f\n", $1, $2}'
	fi
}

location=$(get_location "$1")
[[ -z $location ]] && location=$(curl -s https://ipinfo.io/ip)
[[ $location =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] && type="ip" || type="city"

get_coordinates "$location" "$type"