#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

doc=$(cat <<'EOF'

# geo

Geographical information

`:city|ip`	| Get the 'latitue,longitude' for a give IP address or city

> geo 130.23.11.299		| Get details of given an IP address
> geo "asheville nc"	| Get details a city

EOF
) && export doc && inspect "$1"

# set command default to current IP
if [[ -z $1 ]]; then
	command=$(curl -sL https://ipinfo.io/ip)
else
	command="$1"
	shift 1
fi

case $command in

	* )

		location=$(b/codec url.encode "$command")
		[[ -z $location ]] && location=$(curl -s https://ipinfo.io/ip)
		[[ $location =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]] && type="ip" || type="city"

		[[ $type == "city" ]] && curl -s "https://nominatim.openstreetmap.org/search?format=json&q=$location" | jq -r '.[0].lat + "," + .[0].lon' | awk -F, '{printf "%.2f,%.2f\n", $1, $2}' && exit 0

		curl -s "https://ipinfo.io/$location" | jq -r '.loc' | awk -F, '{printf "%.2f,%.2f\n", $1, $2}' && exit 0

		;;

esac