#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

# print the variable value of a given variable name

# first check if the variable exists
if [ -z "${!1}" ]; then
	echo -n ""
else
	echo "${!1}"
fi