#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

command="$1" && shift

case $command in

	view )

		file_path="$1" && shift # set the file path to the first argument
		width="200"

		while getopts "w:c:h" opt; do
			case $opt in
				w ) width="$OPTARG" ;;
				c ) char="$OPTARG" ;;
				* ) echo "Error: Invalid option" && return 1 ;;
			esac
		done

		# if file_path is not an absolute path, prepend it with the default directory
		if [[ "$file_path" != /* ]]; then
			file_path="$BARE_HOME/.nb/images/$file_path"
		fi

		# using catimg
		declare -a args=()
		[ -n "$width" ] && args+=("-w" "$width")
		[ -n "$char" ] && args+=("-c" "$char")
		args+=("$file_path")

		catimg "${args[@]}"

		;;
		
esac