#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

doc=$(cat <<'EOF'

# image

Work with images, including viewing, converting, and resizing

`view`		| View an image (accepts URLs or file paths)

> image view -u https://example.com/image.jpg -w 100 -h 100 -o /path/to/output.jpg | View an image from a URL

EOF
) && export doc && b/inspect "$@"

command="$1" && shift

case $command in

	view ) doc=$(cat <<'EOF'

# image view

View an image

`-u`	| The URL of the image
`-f`	| The file path of the image
`-o`	| The output file path
`-w`	| The width of the image
`-h`	| The height of the image

> image view -u https://example.com/image.jpg -w 100 -h 100 -o /path/to/output.jpg | View an image from a URL

EOF
		) && export doc && b/inspect "$@"

		width=80
		height=80
		file_path="$BARE_DIR/var/.nb/$1" # set the file path to the first argument

		while getopts "u:f:o:" opt; do
			case $opt in
				u ) url="$OPTARG" ;;
				f ) file_path="$BARE_DIR/var/.nb/$OPTARG" ;; # overwrite the file path if the -f option is used
				o ) output_file_path="$OPTARG" ;;
				* ) echo "Error: Invalid option" && return 1 ;;
			esac
		done

		# using tiv
		# if url, download to tmp file

		if [[ -n $url ]]; then
			tmp_file_path=$(mktemp)
			curl -sL "$url" -o "$tmp_file_path"
			file_path="$tmp_file_path"
		fi

		tiv "$file_path"

		;;
		
esac