#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

# ================================== DOC ===================================
declare doc_name="image"
declare doc_description="Work with images, including viewing, converting, and resizing"
declare -a doc_options=(
	"view"		"View an image (accepts URLs or file paths)"
) && [[ "$1" == '--inspect' ]] && return 0
# ==========================================================================

command="$1" && shift

case $command in

	view )

		# options: -u (URL) -f (file path, relative to $BARE_DIR/var/.nb/images), -w (width), -h (height), -o (output file path)
		# example: ./image view -u https://example.com/image.jpg -w 100 -h 100 -o /path/to/output.jpg

		width=80
		height=80
		file_path="$BARE_DIR/var/.nb/$1" # set the file path to the first argument

		while getopts "u:f:o:" opt; do
			case $opt in
				u ) url="$OPTARG" ;;
				f ) file_path="$BARE_DIR/var/.nb/$OPTARG" ;; # overwrite the file path if the -f option is used
				o ) output_file_path="$OPTARG" ;;
				* ) echo "Error: Invalid option" && return 1 ;;
			esac
		done

		# using tiv
		# if url, download to tmp file

		if [[ -n $url ]]; then
			tmp_file_path=$(mktemp)
			curl -sL "$url" -o "$tmp_file_path"
			file_path="$tmp_file_path"
		fi

		tiv "$file_path"

		;;
		
esac