#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

doc=$(cat <<'EOF'

# import

Import a file or directory into the $BARE_DIR/var/.nb directory

`:1`	| The URL or file path to import
`(:2)`	| The destination path (defaults to $BARE_DIR/var/.nb/imports/$(basename $1))

> b/import https://example.com/image.jpg images/myfolder/imported-image.jpg` | Import a file from a URL
> b/import /path/to/file.txt files/myfolder/imported-file.txt` | Import a file from a file path 

EOF
) && export doc && inspect "$1"

input="$1"
destination_directory="$BARE_DIR/var/.nb/${2:-imports}"

# separate file destination filename and path
if [[ $input == *'/'* ]]; then
	destination_directory="$BARE_DIR/var/.nb/${2%/*}"
	destination_filename="${2##*/}"
fi

destination_path="${destination_directory:+/}$destination_filename"

# make sure the destination directory exists
mkdir -p "$destination_directory"

# check if the input is a URL
if [[ $input == http* ]]; then
	file_name=$(basename "$input")
	curl -sL "$input" -o "$destination_directory/$file_name"
	chown $(whoami) "$destination_directory/$file_name"
# check if the input is a file path
elif [[ -f $input ]]; then
	cp "$input" "$destination_directory"
	chown $(whoami) "$destination_directory/$(basename "$input")"
else
	echo "Error: Invalid URL or file path"
fi