#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

input="$1"
root_dir="$BARE_HOME/.nb"
[[ $input == *'youtube.com'* ]] && ext='mp4' || ext="${input##*.}"
[[ -n $2 ]] && filename="$(basename "$2")" || filename="$(date +%s).$ext"
destination="$root_dir/imports/$filename"

# make sure the destination directory exists
mkdir -p "$(dirname "$destination")"

# check if the input is a URL
if [[ $input == http* ]]; then

	# check if URL is a youtube video (if so, download with youtube-dl)
	if [[ $input == *'youtube.com'* ]]; then
		# check if youtube-dl is installed

		if ! command -v yt-dlp &> /dev/null; then
			read -p "yt-dlp is not installed. Would you like to install it? (y/n) " -n 1 -r
			echo
			if [[ $BARE_OS == 'Linux' ]]; then
				if [[ $REPLY =~ ^[Yy]$ ]]; then
					sudo snap install yt-dlp
				fi
			elif [[ $BARE_OS == 'Darwin' ]]; then
				if [[ $REPLY =~ ^[Yy]$ ]]; then
					brew install yt-dlp
				fi
			fi
		fi

		yt-dlp -o "$destination" "$input" -f "bestvideo[height<=480][ext=mp4][vcodec^=avc]+bestaudio[ext=m4a]/best[ext=mp4]/best" >/dev/null 2>&1
		chown "$(whoami)" "$destination"
		echo "imports:$filename" && exit 0
	else
		destination="$root_dir/imports/$date.$(basename "$input")"
		curl -sL "$input" -o "$destination"
		chown "$(whoami)" "$destination"
	fi
# check if the input is a file path
elif [[ -f $input ]]; then
	cp "$input" "$destination"
	chown "$(whoami)" "$destination"
else
	echo "Error: Invalid URL or file path"
fi