#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

# ================================== DOC ===================================
declare doc_name="lxc"
declare doc_description="Interface with LXC containers"
declare -a doc_options=(
	"create"    "Create a new container"
) && [[ "$1" == '--inspect' ]] && return 0

# if on mac, recommend installing lxc via brew with remote lxd
if [[ "${BARE_OS,,}" == "darwin"* ]]; then
    echo "🌿 It looks like you're on a Mac, which cannot run lxc"
    exit 0
fi

command="$1"
shift

case "$command" in

    create)
	
		doc_name+=" create"
		doc_description="Create a new container"
		declare -a doc_options=(
			"-c"		"  CPU limit"
			"-m"		"  Memory limit"
			"-d"		"  Disk space"
			"-D"		"  Distro"
		) && [[ "$1" == '--inspect' ]] && return 0

        container_name=$1
        shift

        # Default to minimal resource limits and disk space
        cpu_limit="1"
        memory_limit="200MiB"
        disk_space="3GiB"
        distro="ubuntu:22.04"

        # Get opts for resource limits and disk space
        while getopts "c:m:d:D:" opt; do
            case $opt in
                c) cpu_limit="$OPTARG";;
                m) memory_limit="$OPTARG";;
                d) disk_space="$OPTARG";;
                D) distro="$OPTARG";;
                \?) echo "Invalid option: -$OPTARG" && exit 1;;
            esac
        done

        # Step 1: Create the container (without starting it)
        lxc init "$distro" "$container_name" --ephemeral

        # Step 2: Security configurations
        lxc config set "$container_name" security.idmap.isolated true
        lxc config set "$container_name" security.syscalls.blacklist "net_raw"

        # Step 3: Resource limits
        lxc config set "$container_name" limits.cpu "$cpu_limit"
        lxc config set "$container_name" limits.memory "$memory_limit"
        lxc config set "$container_name" limits.memory.swap false

        # Step 4: Disk space
        lxc storage volume create default "$container_name"
        lxc storage volume set default "$container_name" size "$disk_space"

        # Step 5: Start the container
        lxc start "$container_name"
        ;;
    *)
        echo "Unknown command: $command"
        exit 1
        ;;
esac