#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"


# Get the command and length
command=$1
length=${2:-16}

[[ ! $length =~ ^[0-9]+$ ]] && echo "Invalid length: $length. Must be a positive integer." && exit 1;

case $command in
    string ) echo $(LC_ALL=C tr -dc 'a-zA-Z0-9' < /dev/urandom | head -c $length) ;;
    number ) echo $(LC_ALL=C tr -dc '0-9' < /dev/urandom | head -c $length) ;;
    * ) echo "Invalid command: $command" && exit 1 ;;
esac