#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

doc=$(cat <<'EOF'

# research

Go do some research on a given topic, outputs the resulting research markdown

`query`		| The query you want to search for

> research "how to make a cake"	| Search for how to make a cake

EOF
) && export doc && inspect "$1"

# make sure research notebook exists
[[ ! -d $BARE_DIR/var/.nb/research ]] && b/notes notebooks.create "research" > /dev/null 2>&1

query="$1"
time=$(date +%s)

ddgr --noprompt --json --num 7 "$query" > "$BARE_DIR"/var/.nb/research/"$time".tmp.json
results_file="$BARE_DIR"/var/.nb/research/"$time".tmp.json
length=$(jq length "$results_file")

for ((i=0; i<length; i++)); do
	title=$(jq -r ".[$i].title" "$results_file")
	abstract=$(jq -r ".[$i].abstract" "$results_file")
	url=$(jq -r ".[$i].url" "$results_file")
	
	# Skip if the URL is from YouTube or Vimeo (not semantic enough)
	if [[ $url == *"youtube"* || $url == *"vimeo"* || -z $url ]]; then
		continue
	fi

	# Use curl to fetch the webpage content
	curl -sL "$url" -o temp.html

	# Check if curl was successful
	if [[ $? -ne 0 ]]; then
		echo "Error encountered while processing URL: $url"
		continue
	fi

	# Pass the temporary HTML file to xidel
	content=$(xidel temp.html --silent -e 'css("p") | css("h1")')

	# Check if content contains error message
	if [[ $content == *"Error:"* ]]; then
		echo "Error encountered while processing URL: $url"
		continue
	fi

	summary=$(echo "$content" | sumy lex-rank --length=10 --file=<(cat))

	# Remove the temporary HTML file
	rm temp.html
	{
		echo ""
		echo "## $title"
		echo "**URL**: $url"
		echo "**abstract**: $abstract"
		echo ""
		echo "$summary"
		echo ""
		echo ""
		echo "- - - - - - - - - - - - - - - - - - - - -"
	} >> "$BARE_DIR"/var/.nb/research/"$time".tmp.md
done

cat "$BARE_DIR"/var/.nb/research/"$time".tmp.md

rm "$results_file"
rm "$BARE_DIR"/var/.nb/research/"$time".tmp.md