#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

declare doc_name="research"
declare doc_desc="Go do some research on a given topic"
declare -a doc_options=(
	":query" "The query you want to search for"
) && [[ $1 == '--inspect' ]] && return 0

# make sure research notebook exists
[[ ! -d $BARE_DIR/var/.nb/research ]] && b/notes notebooks.create "research" > /dev/null 2>&1

query="$1"
time=$(date +%s)

ddgr --noprompt --json --num 7 "$query" > "$BARE_DIR"/var/.nb/research/"$time".tmp.json
results_file="$BARE_DIR"/var/.nb/research/"$time".tmp.json
length=$(jq length "$results_file")

for ((i=0; i<length; i++)); do
	title=$(jq -r ".[$i].title" "$results_file")
	abstract=$(jq -r ".[$i].abstract" "$results_file")
	url=$(jq -r ".[$i].url" "$results_file")
	
	# Skip if the URL is from YouTube or Vimeo (not semantic enough)
	if [[ $url == *"youtube"* || $url == *"vimeo"* || -z $url ]]; then
		continue
	fi

	content=$(xidel "$url" --silent -e 'css("p") | css("h1")')
	summary=$(echo "$content" | sumy lex-rank --length=10 --file=<(cat))
	{
		echo ""
		echo "## $title"
		echo "**URL**: $url"
		echo "**abstract**: $abstract"
		echo ""
		echo "$summary"
		echo ""
		echo ""
		echo "- - - - - - - - - - - - - - - - - - - - -"
	} >> "$BARE_DIR"/var/.nb/research/"$time".tmp.md
done

cat "$BARE_DIR"/var/.nb/research/"$time".tmp.md

rm "$results_file"
rm "$BARE_DIR"/var/.nb/research/"$time".tmp.md