#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

doc=$(cat <<'EOF'

# script

Manage bare scripts

`list`		| List all bare scripts
`show`		| Print out a bare script
`open`		| Open a bare script
`run`		| Run a bare script
`create`	| Create a bare script

> script list							| List all bare scripts
> script show weather.bare				| Print out a bare script given its filename
> script open invoice-customers.bare	| Open a bare script given its filename

EOF
) && export doc && b/inspect "$@"

command="$1" && shift


case $command in

	list )

		nb use scripts > /dev/null 2>&1
		nb list --no-color --filenames --no-indicator --no-id

		# reset
		nb use home > /dev/null 2>&1
		
		;;

	show ) b/notes show "scripts:$1" ;;
	open ) "${BARE_EDITOR:-vim}" "$BARE_DIR/var/.nb/scripts/$1" ;;
	run ) b/interpret "$1" ;;
	create ) b/notes create -N scripts -T "$1" ;;
	* ) echo "Invalid command: $command" && exit 1 ;;

esac