#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

doc="$(cat <<'EOF'

# script

Manage bare scripts

`list`		| List all bare scripts
`show`		| Print out a bare script
`open`		| Open a bare script
`run`		| Run a bare script
`create`	| Create a bare script

> script list							| List all bare scripts
> script show weather.bare				| Print out a bare script given its filename
> script open invoice-customers.bare	| Open a bare script given its filename

EOF
)" && inspect "$doc" "$1"
# =============================================================================



command="$1" && shift


case $command in

	list ) b/notes list -N "scripts" ;;
	show ) b/notes show "scripts:$1" ;;
	open )
		file="$BARE_HOME/.nb/scripts/$1" && shift
		editor="${2:-${BARE_EDITOR:-vim}}"
		while getopts "e:" opt; do
			case $opt in
				e ) editor="$OPTARG" ;;
				* ) echo "Invalid option: -$OPTARG" >&2 ;;
			esac
		done
		shift $((OPTIND-1))
		# open
		"$editor" "$file"
		;;
	run ) b/interpret "$1" ;;
	create ) b/notes create -N scripts -T "$1" ;;
	* ) echo "Invalid command: $command" && exit 1 ;;

esac