#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

doc="$(cat <<'EOF'

# size

Assigns a value to a variable name

:variable_name		| The name to store the value into
:value				| The value to store

> set "name" "Matthew"		| Assign the value "Matthew" to the variable "name"
> set type = "human"		| Assign the value "human" to the variable "type"
> set age to 30				| Assign the value "30" to the variable "age"

EOF
)" && inspect "$doc" "$1"
# =============================================================================

_name="$1"
# Concatenate all arguments after the second one into the value
_value="${@:3}"

# Check if the third argument is a valid b/* script
if [[ -f "b/$_value" && -x "b/$_value" ]]; then
	# Pass the remaining arguments to b/interpret
	_value=$(./bare "${@:3}" 2>/dev/null)
	# Check the exit status of the script
	if [[ $? -ne 0 ]]; then
		echo "Error: Script failed"
		exit 1
	fi
fi

if [[ $_name =~ [^a-zA-Z0-9_] ]]; then
	echo "Error: Variable name must be one word"
	exit 1
fi

echo "export $_name=\"$_value\"" >> "$HOME/.bare_variables"