#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

# considering a simple bare scripting language for easier composition

# todo: look into lexers, parsers, and interpreters written in bash