#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")/../" && { [ -f lib/init ] && source lib/init || echo "Cannot find lib/init" && exit 1; }

[[ -z $1 ]] && b/usage -t options -w 4 $0 \
    -f "The path to the file to get the size of." && exit 0


ls -lh "$1" | awk '{print $5}'
