#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

# ================================== DOC ===================================
declare doc_name="size"
declare doc_description="Print the size of a file"
declare -a doc_options=(
	":file"		"The file to print the size of"
) && [[ "$1" == '--inspect' ]] && return 0
# ==========================================================================

ls -lh "$1" | awk '{print $5}'
