#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

doc="$(cat <<'EOF'

# ssh

Manage SSH keys

`-l`	| List all SSH keys
`-n`	| Create a new SSH key
`-d`	| Display the default SSH key

> ssh -l		| List all SSH keys
> ssh -n key	| Create a new SSH key
> ssh -d		| Display the default SSH key

EOF
)" && inspect "$doc" "$1"
# =============================================================================



while getopts "ln:d:" opt; do
    case $opt in

        l)
			for key in ~/.ssh/*.pub; do
				sudo basename "$key";
			done 2>/dev/null
            ;;

        n)
            ssh-keygen -t ecdsa -b 521 -f ~/.ssh/"$OPTARG" -C "${2:-}" && cat ~/.ssh/"$OPTARG".pub
            ;;

		d)
			if [ ! -f ~/.ssh/id_ecdsa.pub ]; then
				echo -e "\nNo default key found"
			else
				cat ~/.ssh/id_ecdsa.pub
			fi
			;;
			
		\?) echo -e "\nInvalid option: -$OPTARG" ;;
		
    esac
done