#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

# Get the command and text
command=$1
text=$2

case $command in
	lowercase ) echo "$text" | tr '[:upper:]' '[:lower:]' ;;
	uppercase ) echo "$text" | tr '[:lower:]' '[:upper:]' ;;
	capitalize ) echo "$text" | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}' ;;
	* ) echo "Invalid command: $command" && exit 1 ;;
esac