#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

doc="$(cat <<'EOF'

# weather

Get the current weather for a location

`[:location] today`		| Get today's weather
`[:location] forecast` 	| Get a three-day forecast

> weather today		| Get today's weather
> weather forecast	| Get a three-day forecast

EOF
)" && inspect "$doc" "$1"
# =============================================================================

style="text"
command="today"
color_param="T"

while (( "$#" )); do
	case "$1" in
		-C ) color_param="C" && shift ;;
		-P ) style="pretty" && shift ;;
		today|forecast ) location="$2" && command="$1" && shift 2 ;;
		-J ) command="json" && shift ;;
		* ) location="$1" && shift ;;
	esac
done

[[ $command == 'json' ]] && params="$location?format=j1"
# [[ $command == 'basic' ]] && params="$location?uQF$color&format=%c+%m+%t"
[[ $command == 'today' ]] && params="$location?u0QF$color_param"
[[ $command == 'forecast' ]] && params="$location?u3QF$color_param"

response=$(curl -sL "wttr.in/$params")

declare -A conditions
conditions=(
	["Clear"]="☀️"
	["Sunny"]="☀️"
	["Partly cloudy"]="⛅"
	["Cloudy"]="☁️"
	["Overcast"]="☁️"
	["Mist"]="🌫️"
	["Fog"]="🌫️"
	["Freezing fog"]="🌫️"
	["Patchy rain possible"]="🌦️"
	["Patchy snow possible"]="🌨️"
	["Patchy sleet possible"]="🌨️"
	["Patchy freezing drizzle possible"]="🌨️"
	["Thundery outbreaks possible"]="🌩️"
	["Blowing snow"]="🌨️"
	["Blizzard"]="🌨️"
	["Fog"]="🌫️"
	["Freezing fog"]="🌫️"
	["Patchy light drizzle"]="🌧️"
	["Light drizzle"]="🌧️"
	["Freezing drizzle"]="🌧️"
	["Heavy freezing drizzle"]="🌧️"
	["Patchy light rain"]="🌧️"
	["Light rain"]="🌧️"
	["Moderate rain at times"]="🌧️"
	["Moderate rain"]="🌧️"
	["Heavy rain at times"]="🌧️"
	["Heavy rain"]="🌧️"
	["Light freezing rain"]="🌧️"
	["Moderate or heavy freezing rain"]="🌧️"
	["Light sleet"]="🌨️"
	["Moderate or heavy sleet"]="🌨️"
	["Patchy light snow"]="🌨️"
	["Light snow"]="🌨️"
	["Patchy moderate snow"]="🌨️"
	["Moderate snow"]="🌨️"
	["Patchy heavy snow"]="🌨️"
	["Heavy snow"]="🌨️"
	["Ice pellets"]="🌨️"
	["Light rain shower"]="🌧️"
	["Moderate or heavy rain shower"]="🌧️"
	["Torrential rain shower"]="🌧️"
	["Light sleet showers"]="🌨️"
	["Moderate or heavy sleet showers"]="🌨️"
	["Light snow showers"]="🌨️"
	["Moderate or heavy snow showers"]="🌨️"
)

[[ $style == "text" ]] && {
	# Use sed to extract the necessary details
	weather=$(echo "$response" | sed -n '1p' | cut -c 15- | xargs)
	temperature=$(echo "$response" | sed -n '2p' | cut -c 15- | xargs)
	wind=$(echo "$response" | sed -n '3p' | cut -c 15- | xargs)
	visibility=$(echo "$response" | sed -n '4p' | cut -c 15- | xargs)
	precipitation=$(echo "$response" | sed -n '5p' | cut -c 15- | xargs)

	weather_emoji=${conditions[$weather]}

	# Use emojis to represent wind, precipitation, and visibility
	echo "${weather_emoji:-$weather} ${temperature}, 🌬️ wind ${wind}. 💧 ${precipitation} / 👀 ${visibility}"
	exit 0
} || {
	echo "$response"
	exit 0
}