#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

doc="$(cat <<'EOF'

# web

Starts the bare web interface

> web 	| Start the server

EOF
)" && inspect "$doc" "$1"
# =============================================================================



# Start the server
cd "$BARE_DIR"/lib/www && sqlpage