#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/../lib/init"

doc=$(cat <<'EOF'

# web

Starts the bare web interface

> web 	| Start the server

EOF
) && export doc && b/inspect "$@"

# Start the server
cd "$BARE_DIR"/var/www && sqlpage