#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")/../" && { [ -f lib/init ] && source lib/init; } || { echo "Cannot find lib/init"; exit 1; }

# check that /var/www/ exists
if [ ! -d "/var/www" ]; then
    sudo mkdir -p /var/www
fi