#!/usr/bin/env bash
set +H
set +o histexpand
source "$(dirname "${BASH_SOURCE[0]}")/lib/init"

# if arguments are present, print them and exit
[[ -n $@ ]] && {

	[[ -e "b/$1" ]] && {
		scope="$1" && shift
		"b/$scope" "$@" && exit 0
	}

	echo "$@" && exit 0
}

exit 1