#!/usr/bin/env bash

OS=$(uname)
UPDATED=0
CACHE_FILE="./lib/.deps_cache"

# Create the cache file if it doesn't exist
touch "$CACHE_FILE"

# Define a function to check if a command is available, and install a package if it's not
check_install() {
	cmd=$1
	linux_pkg=$2
	mac_pkg=$3

	# Check the cache file before installing
	if ! grep -q "^$cmd$" "$CACHE_FILE"; then
		if ! [ -x "$(command -v $cmd)" ]; then
			if [ "$OS" = "Linux" ]; then
				if [ $UPDATED -eq 0 ]; then
					sudo apt update
					UPDATED=1
				fi
				if [ -n "$linux_pkg" ]; then
					sudo apt install -y "$linux_pkg"
				fi
			elif [ "$OS" = "Darwin" ]; then
				# Check if Homebrew is installed, if not install it
				if ! [ -x "$(command -v brew)" ]; then
					/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
				fi
				# Check if Git is installed, if not install it
				if ! [ -x "$(command -v git)" ]; then
					brew install git
				fi
				if [ -n "$mac_pkg" ]; then
					if [ $UPDATED -eq 0 ]; then
						brew update
						UPDATED=1
					fi
					brew install "$mac_pkg"
				else
					return 0
				fi
			fi
			# Add the command to the cache file
			echo "$cmd" >> "$CACHE_FILE"
		fi
	fi
}

# Use the function to check and install each package
check_install curl curl curl
check_install feh feh feh
check_install glow glow glow
check_install snap snapd
check_install jq jq jq
check_install lxc lxd
check_install git git git
check_install nginx nginx nginx
check_install ffmpeg ffmpeg ffmpeg
check_install csvlook csvkit csvkit

# Check and install nb
if ! grep -q "^nb$" "$CACHE_FILE"; then
	if ! [ -x "$(command -v nb)" ]; then
		sudo curl -L https://raw.github.com/xwmx/nb/master/nb -o /usr/local/bin/nb && sudo chmod +x /usr/local/bin/nb
		echo nb >> "$CACHE_FILE"
	fi
fi

# Check and install sqlpage
if ! grep -q "^sqlpage$" "$CACHE_FILE"; then
	if ! [ -x "$(command -v sqlpage)" ]; then
		if [ "$OS" = "Linux" ]; then
			sudo curl -s -L -O https://github.com/lovasoa/SQLpage/releases/download/v0.19.1/sqlpage-linux.tgz
			sudo tar -xzf sqlpage-linux.tgz && sudo rm sqlpage-linux.tgz
			sudo mv sqlpage.bin /usr/bin/sqlpage
			sudo chmod 750 /usr/bin/sqlpage
		elif [ "$OS" = "Darwin" ]; then
			if [ $UPDATED -eq 0 ]; then
				brew update
				UPDATED=1
			fi
			brew install sqlpage
		fi
		echo sqlpage >> "$CACHE_FILE"
	fi
fi