#!/usr/bin/env bash
set -e
BARE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)" && export BARE_DIR

cd "$BARE_DIR"

[[ ! -f "$BARE_DIR"/lib/.env ]] && cp "$BARE_DIR"/lib/samples/.env lib/.env

source "$BARE_DIR"/lib/.env
export NB_DIR="$BARE_NOTES_DIR"

source "$BARE_DIR"/lib/colors
source "$BARE_DIR"/lib/deps

function inspect() {

	[[ $1 == '--inspect' ]] && {

		[[ -z "$doc" ]] && echo "No documentation found" && exit 1

		process_line() {
			local prefix=$1
			local max_length=$2
			local line=$3

			if [[ $line == $prefix* ]]; then
				line=$(echo "$line" | tr '\t' ' ' | tr -s ' ' | sed 's/^ *//;s/ *$//')
				IFS='|' read -r first_col second_col <<< "$line"
				if [[ $prefix == '>' ]]; then
					# For examples, strip the > and preceding space, then print the second column as a comment before the command in a code block
					first_col=$(echo "$first_col" | sed 's/^> //')
					printf "\`\`\`bash\n#%s\n%s\n\`\`\`\n" "${second_col}" "${first_col}"
				else
					# For options, print the second column as a column
					format="%-${max_length}s %s\n"
					printf "%s %s\n" "$first_col" "$second_col"
				fi
			fi
		}

		calculate_max_length() {
			local prefix=$1
			local max_length=0

			while IFS= read -r line; do
				if [[ $line == $prefix* ]]; then
					line=$(echo "$line" | tr '\t' ' ' | tr -s ' ' | sed 's/^ *//;s/ *$//')
					IFS='|' read -r first_col second_col <<< "$line"
					length=${#first_col}
					(( length > max_length )) && max_length=$length
				fi
			done <<< "$doc"

			echo $((max_length + 4))
		}

		max_length_options=$(calculate_max_length '\`')
		max_length_examples=$(calculate_max_length '>')

		while IFS= read -r line; do
			line=$(echo "$line" | tr '\t' ' ' | tr -s ' ' | sed 's/^ *//;s/ *$//')
			if [[ $line == \#* ]]; then
				echo "$line"
			elif [[ $line == \`* ]]; then
				[[ -z $options ]] && echo -e "## Options\n" && options=1
				process_line '\`' "$max_length_options" "$line"
			elif [[ $line == \>* ]]; then
				[[ -z $examples ]] && echo -e "## Examples\n" && examples=1
				process_line '>' "$max_length_examples" "$line"
			else
				echo "$line"
			fi
		done <<< "$doc" | glow && exit 0
	}

	return 0
}