#!/usr/bin/env bash
set -e
BARE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)" && export BARE_DIR

cd "$BARE_DIR"

[[ ! -f "$BARE_DIR"/lib/.env ]] && cp "$BARE_DIR"/lib/samples/.env lib/.env

source "$BARE_DIR"/lib/.env
export NB_DIR="$BARE_NOTES_DIR"

source "$BARE_DIR"/lib/colors
source "$BARE_DIR"/lib/deps


declare -A core_env

core_env=(
	["BARE_ENCRYPTION_KEY"]="used for encryption tools"
	["OPENAI_API_KEY"]="used for OpenAI interfacing"
	["STRIPE_SECRET_KEY"]="used for Stripe intrefacing"
	["BARE_EDITOR"]="Used for command line note editing (defaults to vim)"
)

for key in "${!core_env[@]}"; do
	if [[ -z "${!key}" ]]; then
		echo -e "${RED}Error: ${key} is not set${NC}"
		echo -e "${key} is ${core_env[$key]}"
		read -rp "Please enter a value for ${key} (or press enter to skip): " value
		if [[ -n $value ]]; then
			perl -i -pe "s/${key}=.*/${key}=${value}/g" lib/.env
		else
			# set dummy value
			perl -i -pe "s/${key}=.*/${key}=xxxxxxxxxx/g" lib/.env
		fi
	fi
done

# if encryption key is still not set, don't ask user, just set it to a random value
[[ -z "$BARE_ENCRYPTION_KEY" ]] && {
	echo -e "Setting BARE_ENCRYPTION_KEY to a random value"
	perl -i -pe "s/BARE_ENCRYPTION_KEY=.*/BARE_ENCRYPTION_KEY=$(openssl rand -base64 32)/g" lib/.env
}

source "$BARE_DIR"/lib/.env