#!/usr/bin/env bash
set -e
BARE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)" && cd "$BARE_DIR" && export BARE_DIR
BARE_HOME="$HOME/.bare"

# Set up .cache directory
export BARE_CACHE_DIR="$BARE_HOME"/.cache
mkdir -p "$BARE_CACHE_DIR"

# check for ~/.bare home directory
if [[ ! -d $BARE_HOME ]]; then
	mkdir -p "$BARE_HOME"
fi

# check for ~/.bare/.barerc file
if [[ ! -f $BARE_HOME/rc ]]; then
	cp "$BARE_DIR"/lib/samples/.bare/rc "$BARE_HOME"/rc
else
	source "$BARE_HOME"/rc
fi
chmod 600 "$BARE_HOME"/rc # make sure it's only readable and writable by the user

# Find a port for us to use with the web server
BARE_PORT=8080
while lsof -i :$BARE_PORT > /dev/null; do
	BARE_PORT=$((BARE_PORT + 1))
done
export BARE_PORT

# Detect which OS we are using
case "$(uname -s)" in
	Linux*) export BARE_OS=linux ;;
	Darwin*) export BARE_OS=mac ;;
	*) echo "Bare is written for Linux and macOS environments" && exit 1 ;;
esac

source "$BARE_DIR"/lib/colors
source "$BARE_DIR"/lib/deps

# SQLPage config
export port="$BARE_PORT"
export allow_exec=true
export database_URL="sqlite://$BARE_HOME/db"
[[ -f $BARE_HOME/db ]] || touch "$BARE_HOME/db"

# Set up nb to use the correct directory
export BARE_NOTES_DIR="$BARE_HOME"/.nb
export NB_DIR="$BARE_NOTES_DIR"
mkdir -p "$BARE_NOTES_DIR/scripts"
mkdir -p "$BARE_NOTES_DIR/research"
mkdir -p "$BARE_NOTES_DIR/imports"
mkdir -p "$BARE_NOTES_DIR/images"


# =============================================================================

# Common Functions

inspect() {
	doc="$1"
	export doc
	if [[ $2 == "--inspect" ]]; then
		b/inspect "$2" && exit 0
	fi
}

